version: "3.7"

services:
  client:
    image: node:12-stretch
    container_name: client
    working_dir: /app
    volumes:
      - ./client:/app
    ports:
      - 3001:3000
    networks:
      - sandbox
    command: npm start
    stdin_open: true
  proxy:
    image: nginx
    container_name: proxy
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - sandbox
  server:
    build: ./server
    image: server
    container_name: server
    command: tail -f /dev/null
    volumes:
      - ./server/src:/app
    ports:
      - 8000:8000
    networks:
      - sandbox
  db:
    image: postgres:12
    container_name: db
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_API_HOST:-changeme1234}
      - POSTGRES_API_HOST= ${POSTGRES_API_HOST:-db}
      - POSTGRES_API_NAME=${POSTGRES_API_NAME:-api}
      - POSTGRES_API_USER=${POSTGRES_API_USER:-lempira}
      - POSTGRES_API_PASSWORD=${POSTGRES_API_PASSWORD:-changeme1234}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./db/scripts:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    networks:
      - sandbox
  dbadmin:
    image: dpage/pgadmin4
    container_name: dbadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-lempira@email.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-changeme1234}
    ports:
      - 5050:80

volumes:
  postgres_data:

networks:
  sandbox:
    name: sandbox
